---
abstract: 'make a PNG containing a QR code'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-PNG-QRCode
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006001'
resources:
  bugtracker: https://github.com/benkasminbullock/image-png-qrcode/issues
  repository: git://github.com/benkasminbullock/image-png-qrcode.git
version: 0.00_01
